@startuml

partition "Data Coordinator" #lightblue {

}

partition "Federated Orchestrated Cloud"  #lightgrey {
  (*) --> "Deploy Service"
}

partition "Data Coordinator" {
  "Deploy Service" --> "Coordinate Data"
  "Coordinate Data" --> "Evaluate Policies"
  "Evaluate Policies" --> "Determine Method"
  "Determine Method" -> "Move Data"
  "Determine Method" -> "Move Application"
  "Determine Method" ---> "Set Up Data Exchange"
  "Set Up Data Exchange" -> "Create Aggregator"
}

partition "Cloudlet A" #pink {
  "Set Up Data Exchange" -> "Create Exchange Source A"
}

partition "Cloudlet B" #lightgreen {
  "Set Up Data Exchange" -> "Create Exchange Source B"
}

partition "Data Coordinator" {
  "Create Aggregator" ---> "Run Application"
  "Create Exchange Source A" ---> "Run Application"
  "Create Exchange Source B" ---> "Run Application"
}
@enduml
