@startuml

left to right direction

actor :Federated Orchestrated Cloud: as FOC
actor :Cloudlets: as SDI


rectangle "Data Coordinator" #lightblue {
UseCase UC1 as "Move Data"
UseCase UC2 as "Move Application"
UseCase UC3 as "Exchange Data"


FOC --> UC1
FOC --> UC2
FOC --> UC3
UC1 --> SDI
UC2 --> SDI
UC3 --> SDI
}

@enduml
