@startuml

package  "Cloudlet Manager" #lightblue {
    node CloudletManager #white {
        database cloudletDB
        component cloudlet
        cloudlet - cloudletDB
        CLI -- cloudlet
        REST -- cloudlet
        Web -- cloudlet
    }
}
rectangle Ports {
  3100 .. REST
}

package FederatedConnectivity #lightblue {
}

cloud PublicCloud {
    interface C3
}

cloudlet -- C3 : 3000

cloudlet -- FederatedConnectivity

@enduml
