@startuml

package "Cloudlet Manager" #lightblue {
    interface "Cloudlet Manager" {
    }

    CLI ()-- "Cloudlet Manager"
    REST ()-- "Cloudlet Manager"
    Web ()-- "Cloudlet Manager"
}


@enduml
