@startuml

left to right direction

actor :Operations Manager:

rectangle "Cloudlet Manager" #lightblue {
UseCase UC1 as "Add Cloudlet"
UseCase UC2 as "Manage Cloudlet"

UC1 -> UC2
}

:Operations Manager: --> UC1
:Operations Manager: --> UC2

@enduml
