@startuml

left to right direction

skinparam usecase {
  BackgroudnColor #ffffaa
  BackgroundColor<<Main>> #lightblue
}
actor :Operations Manager:

rectangle "Cloudlet Manager" {
UseCase UC1 <<Main>> as "Add Cloudlet"
UseCase UC2  as "Manage Cloudlet"

UC1 --> UC2
}

:Operations Manager: --> UC1
:Operations Manager: --> UC2

@enduml
