@startuml


partition "StackDeveloper"  #cccccc {
  (*) --> "Manage Stack"
}

partition "Cloudlet A" #lightgreen {
  "Manage Stack" --> "Publish Stack"
  "Manage Stack" --> "Destroy Stack"
  "Publish Stack" -> "Propigate Stack"
  "Destroy Stack" --> "Propigate Destruction"
}

partition "Cloudlet B" #pink {
  "Propigate Stack" -> "Publish Stack Local"
  "Propigate Destruction" -> "Destroy Stack Local"
}

@enduml
