@startuml
|StackDeveloper|
start
|#lightgreen|Cloudlet|
:proxy;
|#ffffaa|C3|
fork
:Create Application Stack;
:Modify Application Stack;
:Version Application Stack;
fork again
:Create Service Stack;
:Modify Service Stack;
:Version Service Stack;
:Propagate Service Stack;
|#ffaa44|Remote Cloudlet|
:Version Service Stack;
fork end
|#lightblue|Application Manager|
:Test Application Stack;
:Create an Application;
:Launch an Application in an environment;
:Kill Application and Services;
stop
@enduml
