@startuml

package CloudLet1 #lightgreen {
    class " Cloudlet Manager " as CM1
    class " C3 " {
        Policy Based Scheduling
    }
    class " SDI " {
        VMWare
        OpenStack
    }
    class "Telemetry" as T1
    " C3 " -> " SDI "
    " Cloudlet Manager " -> " C3 "
}

package "Federation Connectivity" as FC #lightblue {
    class "Telemetry Aggregator" as TA
    package "Trust-Management" #ffffff {
      note as N1
      TXT
      Key Management
      end note
    }
    package "Identity Manager" #ffffff {
      note as N2
      AA Security
      Unified identity
      end note
    }
    package "Data Coordinator" #ffffff {
      note as N3
      Trusted / Encrypted
      Replication
      DR/BC
      end note
    }
    package "Federated Orchestrated Cloud" #ffffff {
      note as N4
         Workload movement
         and placement
      end note
    }
}


package Cloudlet2 #pink {
    class "SDI"
    class "C3"
    class "Cloudlet Manager" as CM2
    class "Telemetry" as T2

    "C3" -> "SDI"
    "Cloudlet Manager" -> "C3"
}

T1 --> TA
T2 --> TA
CM1 ---> FC
CM2 --> FC

@enduml

