@startuml

package CloudLet1 #aaffaa {
    class " Cloudlet Manager "
    class " C3 " {
        Policy Based Scheduling
    }
    class " SDI " {
        VMWare
        OpenStack
    }
    " C3 " -> " SDI "
    " Cloudlet Manager " -> " C3 "
}

package "Federation Connectivity" #aaffff {
    package "CIT" #ffffff {
      note as N1
      TXT
      Key Management
      end note
    }
    package "Identity Manager" #ffffff {
      note as N2
      AA Security
      Unified identity
      end note
    }
    package "Data Coordinator" #ffffff {
      note as N3
      Trusted / Encrypted
      Replication
      DR/BC
      end note
    }
    package "Federated Orchestrated Cloud" #ffffff {
      note as N4
         Workload movement
         and placement
      end note
    }
}


package Cloudlet2 #ffaaaa {
    class "SDI"
    class "C3"
    class "Cloudlet Manager"
    "C3" -> "SDI"
    "Cloudlet Manager" -> "C3"
}

" Cloudlet Manager " -- "Federation Connectivity"
"Cloudlet Manager" -- "Federation Connectivity"

@enduml

