@startuml
Actor "actorName" as A

box "Use-Service" #lightblue
participant CLI as CLI
participant Web as Web
participant "cloudlet" as S
A -> CLI : cloudlet-service-monitor()
CLI -> S : service/monitor()
A -> Web : service/monitor()
Web -> S : service/monitor()
end box

@enduml
