@startuml
Actor "actorName" as A

box "Manage-Policies" #lightblue
participant CLI as CLI
participant Web as Web
participant "cloudlet" as S
A -> CLI : cloudlet-policy-list()
CLI -> S : policy/list()
A -> Web : policy/list()
Web -> S : policy/list()
end box

@enduml
