@startuml
Actor "Ops Manager" As Ops

box "Cloud" #lightBlue
participant "Cloudlet Manager" as CMM
participant "CMP" as CMPM
participant "Analytics" as AM
end box
box "Federation" #ffffaa
participant "Federated\nOrchestrated\nCloud" as FOC
participant "Data\nCoordinator" as DC
participant "Identity\nManager" as IM
end box
box "Cloudlet" #lightgreen
participant "Cloudlet Manager" as CMS
participant "CMP" as CMPS
participant "Analytics" as AS
end box

Ops -> CMM: updatePolicy(Policy)
CMM -> AM: updatePolicies(Policy)
CMM -> AM: buildModel
CMM -\ FOC: telemetry

Ops -> CMS: updatePolicy(Policy)
CMS -> AS: updatePolicies(Policy)
CMS -> AS: buildModel
CMS -\ FOC: telemetry
@endum
