@startuml

left to right direction

package CloudLet #ffaaaa {

  class "SNAP (Telemetry)" as STS
  class "Analytics" as AS
  class "CMP" as CMPS
  class "SDI" as SDIS
}
  note as N1
  Information from the analytics.
  Would be used to determine what services should be on the cloud.
  It will also determine what pre-staged Images
  or VMs would be best on the Cloud.
  This information is dynamic.

  A cloud is responsible for itself. Other clouds cannot push
  jobs or services to a cloud. A Cloud pulls services/data/ etc..
  From other clouds and makes  the services available

  Policy will determine how often a Service will be removed
  from the Cloudlet and force other Cloudlets to use the Cloud.
  end note

package "Federated Orchestrated Cloud" #aaffaa {
class "Orchestrator" as OW
class "SNAP (Telemetry) Composite Data Cloud" as STF
class "Analytics" as FOCA
}

package Cloud  #aaaaff {
  class "SDI" as SDIM
  class "SNAP (Telemetry)" as STM
  class "Analytics" as AM
  class "CMP" as CMPM
}
SDIS --> STS
SDIM --> STM
CMPS -> SDIS
CMPM -> SDIM
AS --> STF
STS -> AS
STM -> AM
AM --> STF
STF --> FOCA
FOCA --> OW
OW <--> CMPS
OW <--> CMPM

@enduml
