@startuml
Actor "User" As User

box "Cloud" #lightBlue
participant "CMP" as CMPM
participant "SDI" as SDIM
participant "Analytics" as AM
participant "SNAP" as SM
end box
box "Federation" #ffffaa
participant "Federated\nOrchestrated\nCloud" as FOC
end box
box "Cloudlet" #lightgreen
participant "SDI" as SDIS
participant "Analytics" as AS
participant "SNAP" as SS
end box

loop forever
SDIM -/ SM : telemetry
SM -/ AM : telemetry
AM -> AM : buildModels
AM -/ FOC : telemetry
end
loop forever
SDIS -/ SS : telemetry
SS -/ AS : telemetry
AS -> AS : buildModels
AS -/ FOC : telemetry
end
User -> CMPM: requestInfrastructure(template)
CMPM -> CMPM: checkPolicies(template)
CMPM -> AM: getBestFitCloud(Policies, template)
alt local cloud chosen
CMPM -> SDIM: provisionInfrastructure(template)
end
alt remote cloud chosen
CMPM -> SDIS: provisionInfrastructure(template, identity)
end

@endum
