@startuml
left to right direction

:Stack Developer: as Admin


rectangle "Stack App Manager" {
  Admin --> (Create Application Stack)
  Admin --> (Modify Application Stack)
  Admin --> (Version Application Stack)
  Admin --> (Create Service Template)
  Admin --> (Modify Service Template)
  Admin --> (Version Service Template)
}

rectangle "Application Manager" {
  Admin --> (Test Application Stack)
  (Test Application Stack) --> (Create an Application)
  (Test Application Stack) --> (Launch an Application in an environment)
  (Test Application Stack) --> (Kill Application and Services)
}

@enduml
