@startuml
:Ops Manager: as Ops
:End User: as User
:Stack Developer: as Stack


left to right direction

rectangle "Cloudlet" {
(Register Cloudlet to Cloud) as (RC1)
(Update Local Policies) as (ULP)
(Update Federated Policies) as (USP)
(Use Service) as US
(Register Service) as RS
(Request\nInfrastructure) as RI

Ops --> RC1
Ops --> ULP
User --> RI

}


rectangle "Cloud" {
(Add Cloudlet) as (AC1)
(Update Federated Policies ) as UCP
(Use Service ) as USA
(Register Service ) as RSA
(Request\nInfrastructure ) as RIM
Ops -> AC1
AC1 <--> RC1
Ops -> UCP
UCP <--> USP
RIM <--> RI
User -> RIM
}

User --> US
User --> USA

Stack --> RS
Stack --> RSA
RS <--> RSA

@enduml
