@startuml

left to right direction

:Application Developer: as Dev

rectangle "Application Manager" {
    (Create an Application) as CA
    (Launch application in an environment) as LAE
    (Run Command) as RC
    (View Service and Application Processes) as VSAP
    (Kill Application and Services) as KAS
    (Get Logs) as GL
    (Deploy an Application) as DA
}

Dev --> CA
Dev --> LAE
Dev --> RC
Dev --> VSAP
Dev --> KAS
Dev --> GL
Dev --> DA

@enduml
