@startuml

cloud Cloud #lightgray {
  rectangle Cloudlet #lightblue {
  agent "Cloudlet\nManager"
  agent "Telemetry\nAggregator"
  agent "Security\nManager"
  agent "Data\nCoordinator"
  agent "Identity\nManager"
  }

  cloud "C3" as CL1 #white {
      storage "SDI"
      storage "PaaS"
      storage "Automation\nFramework"
  }
}
cloud Cloud as Cloud2 #lightgray {
  rectangle Cloudlet as C2 #lightblue
  cloud "C3" as C32 #white
  C2 <-> C32
}

cloud Cloud as Cloud3 #lightgray {
  rectangle Cloudlet as Cl3 #lightblue
  cloud "C3" as C33 #white
  Cl3 <-> C33
}

cloud "Edge Device" as Cloud4 #lightgray {
  rectangle Cloudlet as Cl4 #lightblue
  cloud "C3" as C34 #white
  Cl4 <-> C34
}

Cloudlet <--> C2
Cloudlet <-> Cl3
Cloudlet <--> Cl4

@enduml



